#!/bin/awk -f

BEGIN {OFS="\t"};
    # extract sessions only
    { if( !($2 ~ /user/) && !($2 ~ /prompt/) && !(NF == 0) )
        {
            session_id = substr($1, 0, length($1)-2);
            task_token_id = substr($1, length($1)-1, 2);

            print session_id, task_token_id, $2, $3, $4, $5, $6, $7
            }
    }
