#!/bin/bash

unzip dataverse_files.zip
rm dataverse_files.zip
rm starter_code.tar.gz
rm data_en_es.tar.gz

# English learners speaking French
mkdir fr_en
tar -xvzf data_fr_en.tar.gz -C fr_en
rm data_fr_en.tar.gz
./codebase/awk_metadata < fr_en/fr_en.slam.20190204.train > fr_en_metadata.csv
./codebase/awk_sessions < fr_en/fr_en.slam.20190204.train > fr_en_sessions.csv
rm -r fr_en
